# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hear',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True, db_column='date_time')),
                ('artist', models.CharField(db_column='artist', default=0, max_length=255)),
                ('song', models.CharField(db_column='song', default=0, max_length=255)),
                ('tack_id', models.CharField(db_column='track_id', default=0, max_length=255)),
            ],
            options={
                'get_latest_by': 'date_time',
                'verbose_name_plural': 'KG Shazam',
                'ordering': ['-date_time'],
                'verbose_name': 'KG Shazam',
                'db_table': 'hear',
            },
        ),
    ]
