# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0002_hear_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hear',
            name='file',
            field=models.FileField(upload_to='hear'),
        ),
    ]
