# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0004_auto_20170606_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hear',
            options={'verbose_name': 'KG Shazam', 'verbose_name_plural': 'KG Shazam'},
        ),
        migrations.RemoveField(
            model_name='hear',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='hear',
            name='date_time',
        ),
    ]
