# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0005_auto_20170606_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hear',
            options={'get_latest_by': 'date_time', 'ordering': ['-date_time'], 'verbose_name': 'KG Shazam', 'verbose_name_plural': 'KG Shazam'},
        ),
        migrations.AddField(
            model_name='hear',
            name='artist',
            field=models.CharField(db_column='artist', default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hear',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, db_column='date_time', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
