# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0007_auto_20170606_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hear',
            name='file',
        ),
        migrations.AddField(
            model_name='hear',
            name='mpfile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='hear/'),
            preserve_default=False,
        ),
    ]
