# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0008_auto_20170616_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Melody',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('track_id', models.CharField(db_column='track_id', max_length=255, unique=True)),
                ('artist', models.CharField(db_column='artist', max_length=255)),
                ('songname', models.CharField(db_column='songname', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_column='date_added')),
            ],
            options={
                'verbose_name': 'Мелодия',
                'ordering': ['-date_added'],
                'verbose_name_plural': 'Мелодии',
                'get_latest_by': 'date_added',
                'db_table': 'melody',
            },
        ),
        migrations.RemoveField(
            model_name='hear',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='hear',
            name='tack_id',
        ),
        migrations.AlterField(
            model_name='hear',
            name='song',
            field=models.ForeignKey(blank=True, db_column='song', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hear.Melody'),
        ),
    ]
