# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0009_auto_20170617_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melody',
            name='songname',
        ),
        migrations.AddField(
            model_name='melody',
            name='song',
            field=models.CharField(db_column='song', default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
