# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0010_auto_20170617_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melody',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_column='date_added', null=True),
        ),
    ]
