# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0011_auto_20170618_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='melody',
            options={'get_latest_by': 'date_added', 'ordering': ['date_added'], 'verbose_name': 'Мелодия', 'verbose_name_plural': 'Мелодии'},
        ),
        migrations.AlterField(
            model_name='melody',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_column='date_added', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
