# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0015_auto_20170618_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melody',
            name='date_added',
            field=models.DateTimeField(db_column='date_added', default=django.utils.timezone.now),
        ),
    ]
