# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0016_auto_20170618_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='hear',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
