# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0017_hear_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hear',
            name='song',
            field=models.CharField(blank=True, db_column='song', max_length=255, null=True),
        ),
    ]
