# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0019_auto_20170618_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='melody',
            options={'get_latest_by': 'id', 'ordering': ['artist'], 'verbose_name': 'Мелодия', 'verbose_name_plural': 'Мелодии'},
        ),
    ]
