# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0020_auto_20170622_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hear',
            name='detail',
            field=models.CharField(db_column='detail', max_length=255),
        ),
        migrations.AlterField(
            model_name='hear',
            name='mpfile',
            field=models.FileField(db_column='mpfile', upload_to='hear/'),
        ),
        migrations.AlterField(
            model_name='melody',
            name='artist',
            field=models.CharField(db_column='artist', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='melody',
            name='song',
            field=models.CharField(db_column='song', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='melody',
            name='track_id',
            field=models.CharField(db_column='track_id', db_index=True, max_length=255, unique=True),
        ),
    ]
