# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hear', '0022_auto_20170703_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hear',
            name='song',
            field=models.ForeignKey(blank=True, db_column='song', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hear.Melody'),
        ),
    ]
